### ISSUE TITLE
Hosted zone hardcoded?

### ISSUE THREAD

**Issue by pzawadzkipz** [williamsandonz/serverless-website-domain#1]
Hi! 

I hope you are well.
I am having an issue with assigning custom domain to my CloudFormation using your plugin. My IAM role has Route53 permissions needed to execute: **listResourceRecordSets** but it is still failing. 

Is it possible HostedZoneId is hardcoded in the source and that's why I am getting permissions issue?
I tried to find if **Z08994122JHUO1LNKW3WZ** hosted zone id is used by standard but seems like it's not. 

https://github.com/williamsandonz/serverless-website-domain/blob/f3ff7fb03f3c6eb214b29c6af3202f83a78dff45/helper.js#L187

Thank you!

**Comment by williamsandonz** [comment]
Hey @pzawadzkipz , I'm well thanks, hope you are also! I've just taken a quick look and I think you may be right as I can't see any reference of 'Z08994122JHUO1LNKW3WZ' in google, it's possible I forgot to remove my own zoneId before publishing the plugin. Are you able to simply overwrite this string in your node_modules/serverless-website-domain/helper.js with your own hostedZoneId and see if that fixes your issue?

If it fixes issue, I can release a new update of the plugin that uses a new custom.websiteDomain.hostedZoneId variable instead of this hard-coded one. Cheers

**Comment by pzawadzkipz** [comment]
Hi,

It would be perfect if we could do it. I thought that might happened. I am running it through CodeBuild/Deploy directly as I don't have credentials set-up on my local, but I can try to run it on our sandbox account and see if it solves the issue. 

Thanks!

[EDIT]

@williamsandonz I've run my test after making a change you've mentioned and my domain has been assigned correctly. I am having 403 response when I try to access it, but I don't think it's related with the issue we were talking above.

Thank you for help. Let me know once the package has been updated with the changes!
Cheers

**Comment by pzawadzkipz** [comment]
> Hey @pzawadzkipz , I'm well thanks, hope you are also! I've just taken a quick look and I think you may be right as I can't see any reference of 'Z08994122JHUO1LNKW3WZ' in google, it's possible I forgot to remove my own zoneId before publishing the plugin. Are you able to simply overwrite this string in your node_modules/serverless-website-domain/helper.js with your own hostedZoneId and see if that fixes your issue?
> 
> If it fixes issue, I can release a new update of the plugin that uses a new custom.websiteDomain.hostedZoneId variable instead of this hard-coded one. Cheers

Do you know any rough estimates when you will be able to do a release with changes? Just wanted to know if I need to try to find different solutions or stick to your plugin.

**Comment by williamsandonz** [comment]
@pzawadzkipz Sure I can do this sometime today for you and I'll post here once version is up

**Comment by williamsandonz** [comment]
@pzawadzkipz Looks like someone has fixed this in a [fork](https://github.com/PhrontHQ/serverless-website-domain/commit/dbbedba69fc5ee2214d1f1df4091c67c82a6b3c1) aswell, I'm going to merge this fix in

**Comment by pzawadzkipz** [comment]
That's awesome. Many thanks for looking into it :)

**Comment by williamsandonz** [comment]
No worries! @pzawadzkipz 2.0.6 on NPM now

**Comment by williamsandonz** [comment]
@jonogillettt , @PhrontHQ Have merged this in so probably don't need your forks.

**Comment by williamsandonz** [comment]
2.0.6 solves this.
